### ISSUE TITLE
Rerunning check overwrites previous report to filesystem

### ISSUE THREAD

**Issue by marckoene** [ykuijs/SPPeriodicChecks#14]
When using reports instead of/or next to email.
Only one report is stored per day. The latest report overwrites the previous one with the same name.
I would like to have separate reports so you can analyze current and previous reports

**Comment by ykuijs** [comment]
I have changed the file name to include just the date to date and time. Update will be released to Dev soon.

**Comment by ykuijs** [comment]
Fixed in Dev, new version will be released soon (v1.18)
