### ISSUE TITLE
Check50

### ISSUE THREAD

**Issue by marckoene** [ykuijs/SPPeriodicChecks#16]
Please make $numberOfPathsRequired in Check51 adjustable trough config.xml

$numberOfPathsRequired

**Comment by marckoene** [comment]
Maybe create a switch or variable to specify the class of WMI object to retrieve?
Line 23 and 48
we need to use mpio_disk_info instead of HPDSM_PERFINFO

**Comment by ykuijs** [comment]
Hi @marckoene Can you share your version of the check, so I can compare the two versions and make sure the check is generic?

**Comment by ykuijs** [comment]
Update will be available in Dev soon.

**Comment by ykuijs** [comment]
Fixed in Dev, new version will be released soon (v1.18)
