### ISSUE TITLE
Display Environment Name in Subject Email

### ISSUE THREAD

**Issue by marckoene** [ykuijs/SPPeriodicChecks#17]
When checking multiple environments it is hard to differentiate between them based on the subject of the mail since they are the same. Could it be possible to display the environment in the email subject?

**Comment by ykuijs** [comment]
Adding a SubjectSuffix parameter to the config.xml in which you can add a suffix to the email subject. Will be available in Dev soon.

**Comment by ykuijs** [comment]
Fixed in Dev, new version will be released soon (v1.18)
